# To get started with security, check out the documentation:
security:
  # https://symfony.com/doc/current/security/experimental_authenticators.html

  # https://symfony.com/doc/current/security.html#c-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    App\Entity\Core\User: auto

  role_hierarchy:
    ROLE_COLLABORATION: ROLE_INVITED
    ROLE_PROJECT: ROLE_COLLABORATION
    ROLE_ADMIN: ROLE_PROJECT

  # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    users:
      entity:
        class: App\Entity\Core\User
        property: username
        # if you're using multiple entity managers
        # manager_name: customer

  access_control:
    # allow unauthenticated users to access the login form
    - { path: '^/{_locale}/login$', roles: PUBLIC_ACCESS }
    # but require authentication for all other routes
    - { path: '^/(?!.*login$)', roles: IS_AUTHENTICATED_FULLY }


  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: users
      form_login:
        login_path: login
        check_path: login
      logout:
        path: logout
        target: login
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800 # 1 week in seconds
        path: /
        name: remember_logged_in
        secure: true
