parameters:
    admin:
        # definition de la forme générale des clés étrangères
        fk_name:
            fixe_fk_delimiter: '_'
            prefixe_fk: 'id'
            suffixe_fk: ''
        #            